version: '2'
services:
  core:
    image: centos
    command: python inphinity/tests.py
    hostname: core
    networks:
      - mynet
    tty: true
    volumes:
      - ../inphinity/data:/data
      - ../inphinity:/inphinity

  hmmer:
    build: ../dockers/hmmer
    hostname: hmmer
    links:
    - core
    tty: true
    networks:
      - mynet

  database:
    build: ../dockers/database
    links:
    - core
    tty: true
    environment:
    - MYSQL_ROOT_PASSWORD=SecretPasswordInphinity
    networks:
      - mynet

networks:
  mynet:
    driver: bridge