version: '2'
services:
  core:
    build: ../dockers/core
    command: sh run.sh
    hostname: core
    networks:
      - mynet
    tty: true
    volumes:
      - ../inphinity/data:/data:Z
      - ../inphinity:/inphinity:Z
    privileged: true

  #docker run -v ../inphinity:/tmp/inphinity --privileged core "sh run.sh"

  hmmer:
    build: ../dockers/hmmer
    hostname: hmmer
    links:
      - core
    tty: true
    networks:
      - mynet

  database:
    build: ../dockers/database
    links:
      - core
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=SecretPasswordInphinity
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    networks:
      - mynet

networks:
  mynet:
    driver: bridge