version: '2'
services:
  database:
    build: ../dockers/database
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=SecretPasswordInphinity
      - MYSQL_USER=inphinity
      - MYSQL_PASSWORD=SecretPasswordInphinity
      - MYSQL_DATABASE=phage_bact
    ports:
      - 3306:3306
    networks:
      - mynet
    container_name: database
    #entrypoint: ['bash']

  core:
    build: ../dockers/core
    command: sh run.sh
    hostname: core
    networks:
      - mynet
    tty: true
    volumes:
      - ../inphinity/data:/data:Z
      - ../inphinity:/inphinity:Z
    privileged: true
    links:
      - database:database
    depends_on:
      - database
    container_name: core

  #docker run -v ../inphinity:/tmp/inphinity --privileged core "sh run.sh"

  hmmer:
    build: ../dockers/hmmer
    hostname: hmmer
    links:
      - core
    tty: true
    networks:
      - mynet



networks:
  mynet:
    driver: bridge