version: '2'
services:
  database:
    build: ../dockers/database
    tty: true
    environment:
      #TODO: remove ???
      MYSQL_ROOT_PASSWORD: SecretPasswordInphinity
      MYSQL_USER: inphinity
      MYSQL_PASSWORD: SecretPasswordInphinity
      MYSQL_DATABASE: phage_bact
    ports:
      - 3309:3306
    networks:
      mynet:
        ipv4_address: 172.25.0.102
    container_name: inphinity-database
    volumes: #needed to acces db from python! Why ?
      - /inphinity-data/mysql:/var/lib/mysql

  core:
    build: ../dockers/core
    #command: sudo sh run.sh
    hostname: core
    networks:
      mynet:
        ipv4_address: 172.25.0.101
    tty: true
    volumes:
      - ../inphinity:/inphinity:Z
      - ../dockers/core/data-hmm:/data-hmm:Z
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    links:
      - database:database
    depends_on:
      - database
    container_name: inphinity-core

  hmmer:
    build: ../dockers/hmmer
    image: inphinity-hmmer
    hostname: hmmer
    links:
      - core
    tty: true
    networks:
      - mynet
    container_name: inphinity-hmmer




networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24